[package]
name = "joy-workflows-core"
version = "0.1.0"
edition = "2021"
description = "Shared automation-first Joy workflow state used by cross-framework demos"
license = "MIT OR Apache-2.0"

[dependencies]
mui-headless = { path = "../../crates/mui-headless" }
mui-joy = { path = "../../crates/mui-joy", default-features = false }
mui-system = { path = "../../crates/mui-system" }

[features]
default = []
