[package]
name = "layout_box_leptos"
version = "0.1.0"
edition = "2021"
publish = false
license.workspace = true

[lib]
name = "layout_box_leptos"
path = "src/lib.rs"

[[bin]]
name = "layout-box-leptos"
path = "src/main.rs"

[dependencies]
leptos.workspace = true
rustic-ui-system = { path = "../../crates/rustic-ui-system", features = ["leptos"] }
serde_json.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = ["Window"] }

[features]
default = ["csr"]
csr = []
ssr = []


