---
title: "{{component_pascal}}"
description: "Automation-first scaffold generated by `cargo xtask new-component`."
automationId: "{{automation_id}}"
---

import Alert from '@mui/material/Alert';

<Alert severity="info">
  This page was generated automatically. Replace the guidance once the
  `{{component_pascal}}` component ships. Keep the automation identifier metadata in sync with the
  Rust and TypeScript scaffolds until real docs land.
</Alert>

## Implementation tracker

- [ ] Connect to the headless state machine in `crates/rustic-ui-headless/src/{{component_snake}}.rs`.
- [ ] Bridge Material adapters in `crates/rustic-ui-material/src/{{component_snake}}.rs`.
- [ ] Export React telemetry helpers from `packages/mui-material/src/{{component_pascal}}/RusticAdapter.tsx`.
- [ ] Author integration tests replacing the ignored placeholders emitted by the generator.
- [ ] Update this page with usage examples, analytics notes, and SSR expectations.

## Automation contract

| Surface | Automation root | Notes |
| --- | --- | --- |
| Headless | `{{automation_id}}` | Update if the state machine exposes additional selectors. |
| Material | `{{automation_id}}` | Ensure framework adapters mirror docs and tests. |
| React | `{{automation_id}}` | Keep telemetry payload names aligned with Rust instrumentation. |

## Next steps

1. Implement the headless state machine transitions, returning structured
   telemetry events for analytics pipelines.
2. Feed the Material adapters from the headless crate, stamping
   `data-rustic-*` selectors using the automation root captured above.
3. Extend the docs with runnable examples and link to the regression tests that
   protect the new component.
