//! Material adapter smoke-test placeholder for `{{component_pascal}}`.
//!
//! Generated by `cargo xtask new-component` so new components land with a ready
//! made test file. Replace the ignored test with coverage that exercises the
//! actual adapter once it exists. Keeping the automation identifier assertion in
//! place ensures the docs, Rust code, and TypeScript adapter stay aligned.

#[test]
#[ignore = "Replace with real {{component_pascal}} adapter assertions"]
fn {{component_snake}}_material_adapter_emits_expected_automation_root() {
    let automation_root = "{{automation_id}}";
    assert_eq!(automation_root, "{{automation_id}}", "update docs + adapters if the automation root changes");
}
