/**
 * Automation-focused adapter scaffold for `{{component_pascal}}`.
 *
 * Generated by `cargo xtask new-component` so React and other JS runtimes share
 * the same automation contract as the Rust headless state. Replace the stubbed
 * return value with a concrete implementation once the Material adapters land.
 */
export interface {{component_pascal}}AdapterTelemetry {
  /**
   * Stable automation identifier mirrored from the Rust constants generated in
   * `crates/rustic-ui-headless` and `crates/rustic-ui-material`.
   */
  automationRoot: string;
  /**
   * Capture TODO items discovered during scaffolding. Keeping the notes inline
   * makes it straightforward for QA and documentation teams to trace pending
   * follow-ups.
   */
  notes: string[];
}

export function create{{component_pascal}}AdapterTelemetry(): {{component_pascal}}AdapterTelemetry {
  return {
    automationRoot: '{{automation_id}}',
    notes: [
      'Thread automationRoot into the rendered data-automation-id attributes.',
      'Emit telemetry payloads that mirror the Rust instrumentation delegates.',
      'Link implementation docs at docs/src/pages/system/components/{{component_kebab}}.mdx.',
    ],
  };
}
