/**
 * Storybook harness placeholder for `{{component_pascal}}`.
 *
 * Generated by `cargo xtask new-component` so Storybook stories immediately
 * consume the same automation identifiers and telemetry commentary as the
 * Rust + TypeScript scaffolds. Replace the JSX stub once real renderers exist,
 * but keep the automation-root contract intact so visual regression suites and
 * docs snippets remain aligned.
 */
import * as React from 'react';
import { create{{component_pascal}}AdapterTelemetry } from './RusticAdapter';

/**
 * Canonical metadata snapshot Storybook instances can spread into
 * `export default` to register the story group. We avoid importing Storybook
 * types directly so repositories without Storybook installed can still compile
 * the generated scaffolds. Downstream teams can refine the shape based on the
 * specific Storybook major version they standardise on.
 */
export const {{component_pascal}}StoryMeta = {
  title: 'RusticUI/Material/{{component_pascal}}',
  parameters: {
    layout: 'centered',
    docs: {
      description: {
        component:
          'Replace this description with framework-specific guidance once the component ships.',
      },
    },
  },
} as const;

/**
 * Minimal playground render so designers and engineers can visualise the
 * automation wiring. The markup intentionally mirrors the telemetry payloads
 * exposed by `create{{component_pascal}}AdapterTelemetry` to keep QA and visual
 * regression tools honest while the real component is under construction.
 */
export function {{component_pascal}}StoryPlayground(): React.ReactElement {
  const telemetry = create{{component_pascal}}AdapterTelemetry();

  return (
    <section
      aria-labelledby="{{component_kebab}}-story-heading"
      data-automation-root={telemetry.automationRoot}
      data-storybook-contract="{{automation_id}}"
      style={{
        display: 'grid',
        gap: '1rem',
        padding: '2rem',
        border: '1px dashed currentColor',
        borderRadius: '1rem',
      }}
    >
      <header>
        <h2 id="{{component_kebab}}-story-heading">{{component_pascal}} (Story placeholder)</h2>
        <p>
          Replace this placeholder once the component renders real UI. Keep the
          automation ID contract intact so Storybook knobs and automated
          screenshots remain in sync with Rust and docs surfaces.
        </p>
      </header>
      <pre
        aria-label="Automation metadata"
        style={{
          background: 'var(--storybook-background, #0b0d0f)',
          color: 'var(--storybook-foreground, #f8fafc)',
          padding: '1rem',
          borderRadius: '0.75rem',
          maxWidth: '36rem',
        }}
      >
        {JSON.stringify(telemetry, null, 2)}
      </pre>
    </section>
  );
}
