packages:
  # Legacy Material UI sources are archived under `archives/mui-packages/` to keep Node-centric
  # tooling isolated from the Rust-first workspace. Including the directory here lets pnpm filter
  # against those snapshots without pointing new contributors at the deprecated layout.
  - archives/mui-packages/*
  - archives/mui-packages/*/test
  # Active Rust and TypeScript utilities that continue to evolve alongside the archives.
  - packages/*
  - packages-internal/*
  - docs
  - test
  - test/*
  - apps/*

patchedDependencies:
  styled-components: patches/styled-components.patch

onlyBuiltDependencies:
  - '@vvago/vale'

engineStrict: true
