[package]
name = "mui-yew-example"
version = "0.1.0"
edition = "2021"

[dependencies]
yew.workspace = true
mui-system = { path = "../../crates/rustic-ui-system", features = ["yew"] }
tokio = { workspace = true, optional = true }

[features]
default = ["csr"]
csr = []
ssr = ["tokio"]
