import * as React from 'react';
import type { GetStaticProps, InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { promises as fs } from 'fs';
import path from 'path';
import Container from '@mui/material/Container';
import Paper from '@mui/material/Paper';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Typography from '@mui/material/Typography';
import Alert from '@mui/material/Alert';

interface ScenarioMeasurement {
  id: string;
  crate_name: string;
  display_name: string;
  description: string;
  default_features: boolean;
  features: string[];
  feature_label: string;
  command_summary: string;
  is_baseline: boolean;
  size_bytes: number;
  size_kib: number;
  artifact: string;
  delta_bytes?: number | null;
  delta_kib?: number | null;
  delta_percent?: number | null;
}

interface BundleReport {
  generated_at: string;
  generated_at_unix: number;
  target_dir: string;
  scenarios: ScenarioMeasurement[];
  notes: string[];
}

type BundleCostProps = {
  report: BundleReport;
};

const formatDelta = (value?: number | null): string => {
  if (value === null || value === undefined) {
    return '0.00';
  }
  const formatted = value.toFixed(2);
  if (value > 0) {
    return `+${formatted}`;
  }
  return formatted;
};

export const getStaticProps: GetStaticProps<BundleCostProps> = async () => {
  const filePath = path.join(process.cwd(), 'performance', 'bundle-costs.json');
  const raw = await fs.readFile(filePath, 'utf8');
  const report = JSON.parse(raw) as BundleReport;

  report.scenarios.sort((a, b) => a.display_name.localeCompare(b.display_name));

  return {
    props: {
      report,
    },
  };
};

const BundleCostsPage = ({ report }: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <React.Fragment>
      <Head>
        <title>RusticUI bundle cost dashboard</title>
        <meta
          name="description"
          content="Feature-flag aware bundle size report generated by cargo xtask bundle-report."
        />
      </Head>
      <Container maxWidth="lg" sx={{ py: 6 }}>
        <Typography variant="h2" gutterBottom>
          Bundle cost telemetry
        </Typography>
        <Typography paragraph>
          The data below is exported by{' '}
          <code>cargo xtask bundle-report</code> and refreshed on every CI run that exercises the
          Criterion benchmarks. Pair it with the{' '}
          <Link href="/testing/coverage-overview">cross-suite coverage dashboard</Link> to understand
          how new features affect both bundle size and verification depth.
        </Typography>
        <Alert severity="info" sx={{ mb: 3 }}>
          JSON and Markdown sources are committed under{' '}
          <code>docs/performance/bundle-costs.&#123;json,md&#125;</code>. The Markdown variant is also
          published as part of the docs site to give product teams human-friendly deltas.
        </Alert>
        <Typography variant="body2" color="text.secondary" gutterBottom>
          Generated at {report.generated_at} (unix {report.generated_at_unix}). Artifacts compiled with
          release profile under <code>{report.target_dir}</code>.
        </Typography>
        <TableContainer component={Paper} elevation={0} variant="outlined">
          <Table size="small" aria-label="Bundle size scenarios">
            <TableHead>
              <TableRow>
                <TableCell>Scenario</TableCell>
                <TableCell>Crate</TableCell>
                <TableCell>Features</TableCell>
                <TableCell align="right">Size (KiB)</TableCell>
                <TableCell align="right">Δ KiB</TableCell>
                <TableCell align="right">Δ %</TableCell>
                <TableCell>Description</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {report.scenarios.map((scenario) => (
                <TableRow key={scenario.id} hover>
                  <TableCell component="th" scope="row">
                    {scenario.display_name}
                  </TableCell>
                  <TableCell>{scenario.crate_name}</TableCell>
                  <TableCell>{scenario.feature_label}</TableCell>
                  <TableCell align="right">{scenario.size_kib.toFixed(2)}</TableCell>
                  <TableCell align="right">{formatDelta(scenario.delta_kib ?? 0)}</TableCell>
                  <TableCell align="right">{formatDelta(scenario.delta_percent ?? 0)}</TableCell>
                  <TableCell>{scenario.description}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
        <Typography variant="h3" sx={{ mt: 4 }} gutterBottom>
          Methodology
        </Typography>
        <Typography component="div" paragraph>
          <ul>
            {report.notes.map((note) => (
              <li key={note}>{note}</li>
            ))}
          </ul>
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Need the raw numbers for automation? Download the machine-readable payload from{' '}
          <Link href="/performance/bundle-costs.json">bundle-costs.json</Link>.
        </Typography>
      </Container>
    </React.Fragment>
  );
};

export default BundleCostsPage;
