[package]
name = "rustic_ui_leptos_example"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos.workspace = true
rustic-ui-system = { path = "../../crates/rustic-ui-system", features = ["leptos"] }
tokio = { workspace = true, optional = true }

[features]
default = ["csr"]
csr = []
ssr = ["tokio"]
