[package]
name = "rustic_ui_leptos_example"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos.workspace = true
leptos_router.workspace = true
rustic-ui-system = { path = "../../crates/rustic-ui-system", features = ["leptos"] }
tokio = { workspace = true, optional = true }
mui-shared = { path = "../mui-shared", features = ["automation", "routes", "layout", "theme"] }

[features]
default = ["csr"]
csr = []
ssr = ["tokio"]
