//! Material aware renderer for the layout [`BoxState`](rustic_ui_headless::box::BoxState).
//!
//! The Material crate intentionally keeps layout rendering logic in Rust so
//! every adapter (React, Yew, Leptos, etc.) can share the same declarative
//! pipeline.  The headless crate already performs breakpoint resolution; this
//! module merely converts that data into deterministic CSS variable maps and
//! inline style strings that are safe to embed in server rendered markup.  By
//! funnelling the formatting work through a shared function we remove a whole
//! class of copy/paste errors where adapters forget to duplicate ARIA or styling
//! logic.

use std::collections::BTreeMap;

use rustic_ui_headless::r#box::{BoxEvaluation, BoxState};

use crate::render_helpers::{
    collect_responsive_variables, css_variables_to_style, normalise_css_token,
    normalise_spacing_token, CssVariableMap,
};

/// Output generated by [`render_box`].
///
/// * [`css_variables`] exposes the underlying map so adapters that prefer
///   declarative stylesheets (e.g. CSS-in-JS) can register the values using their
///   own abstractions.
/// * [`inline_style`] concatenates the same data into a SSR friendly string that
///   can be written directly to `style="..."`.  The helper is primarily used by
///   server centric frameworks which stream HTML during the first request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BoxRenderOutput {
    css_variables: CssVariableMap,
    inline_style: String,
}

impl BoxRenderOutput {
    /// Returns the computed CSS variable map.
    #[inline]
    pub fn css_variables(&self) -> &BTreeMap<String, String> {
        &self.css_variables
    }

    /// Returns the pre-serialised inline style string.
    #[inline]
    pub fn inline_style(&self) -> &str {
        &self.inline_style
    }
}

/// Render the [`BoxState`] into CSS variables and a SSR friendly style string.
///
/// The renderer walks through every breakpoint registered on the state machine
/// and stores the evaluated padding, margin and background tokens under the
/// `--rustic_ui_box_*` namespace.  The output intentionally avoids mutating the
/// values so organisations that plug in custom design tokens see the exact
/// strings they supplied.  Empty tokens are normalised to `0px` (for spacing)
/// and `transparent` (for backgrounds) to keep the generated CSS valid.  The
/// resulting map is fed into [`css_variables_to_style`] to produce deterministic
/// inline markup for SSR.
#[must_use]
pub fn render_box(state: &BoxState) -> BoxRenderOutput {
    let mut css_variables = CssVariableMap::new();

    collect_responsive_variables(
        &mut css_variables,
        "box",
        state.breakpoints(),
        |breakpoint| {
            let evaluation = state.evaluate_for(breakpoint);
            box_tokens_for_breakpoint(&evaluation)
        },
    );

    let inline_style = css_variables_to_style(&css_variables);

    BoxRenderOutput {
        css_variables,
        inline_style,
    }
}

fn box_tokens_for_breakpoint(evaluation: &BoxEvaluation<'_>) -> Vec<(&'static str, String)> {
    let mut tokens = Vec::with_capacity(4);

    tokens.push((
        "padding",
        normalise_spacing_token(evaluation.padding.as_str()),
    ));
    tokens.push((
        "margin",
        normalise_spacing_token(evaluation.margin.as_str()),
    ));
    tokens.push((
        "background",
        normalise_css_token(evaluation.background.as_str(), "transparent"),
    ));

    // Including the computed role as a CSS variable allows automation and
    // advanced styling hooks to reference the semantic intent of the Box without
    // consulting JavaScript.  Storing it per breakpoint keeps the API symmetric
    // with the other tokens even though the role currently does not change per
    // breakpoint.
    tokens.push(("role", evaluation.role.as_str().to_string()));

    if matches!(
        evaluation.breakpoint,
        rustic_ui_headless::layout::Breakpoint::Base
    ) {
        // Surface the raw breakpoint token at base scope so adapters can derive
        // deterministic automation hooks without repeating the naming logic.
        tokens.push(("active_breakpoint", evaluation.breakpoint.as_token().into()));
    }

    tokens
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustic_ui_headless::layout::{BreakpointConfig, ResponsiveValue};

    #[test]
    fn render_box_generates_css_variables() {
        let tokens = rustic_ui_headless::r#box::BoxTokens {
            padding: ResponsiveValue::from(String::from("1rem")),
            margin: ResponsiveValue::from(String::from("0")),
            background: ResponsiveValue::from(String::from("var(--surface)")),
        };
        let state = BoxState::new(tokens, BreakpointConfig::material());

        let output = render_box(&state);

        assert!(output
            .css_variables()
            .contains_key("--rustic_ui_box_padding"));
        assert!(output.inline_style().contains("--rustic_ui_box_padding"));
    }
}
