//! Material aware renderer for the layout [`BoxState`](rustic_ui_headless::box::BoxState).
//!
//! The Material crate intentionally keeps layout rendering logic in Rust so
//! every adapter (React, Yew, Leptos, etc.) can share the same declarative
//! pipeline.  The headless crate already performs breakpoint resolution; this
//! module merely converts that data into deterministic CSS variable maps and
//! inline style strings that are safe to embed in server rendered markup.  By
//! funnelling the formatting work through a shared function we remove a whole
//! class of copy/paste errors where adapters forget to duplicate ARIA or styling
//! logic.

use std::collections::BTreeMap;

use rustic_ui_headless::r#box::{BoxEvaluation, BoxState};

use crate::render_helpers::{
    collect_responsive_variables, css_variables_to_style, normalise_css_token,
    normalise_spacing_token, CssVariableMap,
};

/// Output generated by [`render_box`].
///
/// * [`css_variables`] exposes the underlying map so adapters that prefer
///   declarative stylesheets (e.g. CSS-in-JS) can register the values using their
///   own abstractions.
/// * [`inline_style`] concatenates the same data into a SSR friendly string that
///   can be written directly to `style="..."`.  The helper is primarily used by
///   server centric frameworks which stream HTML during the first request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BoxRenderOutput {
    css_variables: CssVariableMap,
    inline_style: String,
}

impl BoxRenderOutput {
    /// Returns the computed CSS variable map.
    #[inline]
    pub fn css_variables(&self) -> &BTreeMap<String, String> {
        &self.css_variables
    }

    /// Returns the pre-serialised inline style string.
    #[inline]
    pub fn inline_style(&self) -> &str {
        &self.inline_style
    }
}

/// Render the [`BoxState`] into CSS variables and a SSR friendly style string.
///
/// The renderer walks through every breakpoint registered on the state machine
/// and stores the evaluated padding, margin and background tokens under the
/// `--rustic_ui_box_*` namespace.  The output intentionally avoids mutating the
/// values so organisations that plug in custom design tokens see the exact
/// strings they supplied.  Empty tokens are normalised to `0px` (for spacing)
/// and `transparent` (for backgrounds) to keep the generated CSS valid.  The
/// resulting map is fed into [`css_variables_to_style`] to produce deterministic
/// inline markup for SSR.
#[must_use]
pub fn render_box(state: &BoxState) -> BoxRenderOutput {
    let mut css_variables = CssVariableMap::new();

    collect_responsive_variables(
        &mut css_variables,
        "box",
        state.breakpoints(),
        |breakpoint| {
            let evaluation = state.evaluate_for(breakpoint);
            box_tokens_for_breakpoint(&evaluation)
        },
    );

    let inline_style = css_variables_to_style(&css_variables);

    BoxRenderOutput {
        css_variables,
        inline_style,
    }
}

fn box_tokens_for_breakpoint(evaluation: &BoxEvaluation<'_>) -> Vec<(&'static str, String)> {
    let mut tokens = Vec::with_capacity(4);

    tokens.push((
        "padding",
        normalise_spacing_token(evaluation.padding.as_str()),
    ));
    tokens.push((
        "margin",
        normalise_spacing_token(evaluation.margin.as_str()),
    ));
    tokens.push((
        "background",
        normalise_css_token(evaluation.background.as_str(), "transparent"),
    ));

    // Including the computed role as a CSS variable allows automation and
    // advanced styling hooks to reference the semantic intent of the Box without
    // consulting JavaScript.  Storing it per breakpoint keeps the API symmetric
    // with the other tokens even though the role currently does not change per
    // breakpoint.
    tokens.push(("role", evaluation.role.as_str().to_string()));

    if matches!(
        evaluation.breakpoint,
        rustic_ui_headless::layout::Breakpoint::Base
    ) {
        // Surface the raw breakpoint token at base scope so adapters can derive
        // deterministic automation hooks without repeating the naming logic.
        tokens.push(("active_breakpoint", evaluation.breakpoint.as_token().into()));
    }

    tokens
}

/// Props shared by every framework adapter.
///
/// The [`BoxState`] already abstracts controlled and uncontrolled usage through
/// its internal control strategy.  Adapters accept a reference to the state so
/// reactive frameworks can either hold the state in a signal (controlled) or
/// let the state live locally inside the adapter (uncontrolled).  The renderer
/// simply reads the latest snapshot which keeps the mapping to the headless API
/// deterministic.
#[derive(Clone, Copy, Debug)]
pub struct BoxAdapterProps<'a> {
    /// Headless box state machine driving layout evaluation.
    pub state: &'a BoxState,
}

impl<'a> BoxAdapterProps<'a> {
    /// Convenience constructor so integrators can express intent without struct
    /// literal syntax.
    #[inline]
    pub fn new(state: &'a BoxState) -> Self {
        Self { state }
    }
}

/// Internal helper used by every adapter module.
///
/// The function keeps the controlled/uncontrolled behaviour consistent by
/// always delegating to [`render_box`].  Framework specific wrappers simply call
/// this helper so server rendered React, client side Yew or signal driven
/// Sycamore pipelines all render identical CSS variables.
#[cfg_attr(
    not(any(
        feature = "react",
        feature = "yew",
        feature = "leptos",
        feature = "dioxus",
        feature = "sycamore"
    )),
    allow(dead_code)
)]
fn render_box_with_props(props: BoxAdapterProps<'_>) -> BoxRenderOutput {
    // Delegating straight to the shared renderer ensures the adapter never goes
    // out of sync with the canonical SSR output and keeps hydration byte-perfect.
    render_box(props.state)
}

/// React SSR adapter wrapping [`render_box`].
#[cfg(feature = "react")]
pub mod react {
    use super::*;

    /// Generate deterministic CSS variables for React's server rendering stage.
    ///
    /// Enterprise teams often run this inside Node based renderers before
    /// handing control to React on the client.  The adapter intentionally avoids
    /// mutating the state; React should own the control flow and provide updated
    /// [`BoxState`] snapshots whenever props change.  On hydration the browser
    /// sees the exact same inline style string which prevents checksum
    /// mismatches.
    pub fn render(props: BoxAdapterProps<'_>) -> BoxRenderOutput {
        super::render_box_with_props(props)
    }
}

/// Yew adapter exposing [`render_box`] behind the `yew` feature flag.
#[cfg(feature = "yew")]
pub mod yew {
    use super::*;

    /// Produce CSS variables for inclusion in a `<style>` tag or inline `style`
    /// attribute while respecting Yew's reactive lifecycles.  Callers typically
    /// store the [`BoxState`] inside `use_state` (controlled) or build it on the
    /// fly per render (uncontrolled); both flows surface the latest snapshot to
    /// this helper which in turn mirrors the shared SSR renderer.
    pub fn render(props: BoxAdapterProps<'_>) -> BoxRenderOutput {
        super::render_box_with_props(props)
    }
}

/// Leptos adapter bridging reactive signals to [`render_box`].
#[cfg(feature = "leptos")]
pub mod leptos {
    use super::*;

    /// Invoke the shared renderer using the latest headless snapshot.  Because
    /// Leptos signals re-run dependents automatically, feeding the [`BoxState`]
    /// through this helper keeps controlled signal driven flows aligned with the
    /// headless behaviour without writing imperative glue code.
    pub fn render(props: BoxAdapterProps<'_>) -> BoxRenderOutput {
        super::render_box_with_props(props)
    }
}

/// Dioxus adapter for layout SSR/hydration pipelines.
#[cfg(feature = "dioxus")]
pub mod dioxus {
    use super::*;

    /// Dioxus ships the same [`BoxState`] between server and client.  The
    /// adapter simply calls into the shared renderer, guaranteeing that the
    /// inline style string matches across SSR and subsequent mutations triggered
    /// by controlled props.
    pub fn render(props: BoxAdapterProps<'_>) -> BoxRenderOutput {
        super::render_box_with_props(props)
    }
}

/// Sycamore adapter mirroring the other framework implementations.
#[cfg(feature = "sycamore")]
pub mod sycamore {
    use super::*;

    /// Sycamore's reactive scopes can own the [`BoxState`] directly or receive
    /// it from a parent owner.  In both cases we route through the shared
    /// renderer so SSR output and client side recomputation stay perfectly
    /// aligned for enterprise grade snapshot testing.
    pub fn render(props: BoxAdapterProps<'_>) -> BoxRenderOutput {
        super::render_box_with_props(props)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustic_ui_headless::layout::{BreakpointConfig, ResponsiveValue};

    #[test]
    fn render_box_generates_css_variables() {
        let tokens = rustic_ui_headless::r#box::BoxTokens {
            padding: ResponsiveValue::from(String::from("1rem")),
            margin: ResponsiveValue::from(String::from("0")),
            background: ResponsiveValue::from(String::from("var(--surface)")),
        };
        let state = BoxState::new(tokens, BreakpointConfig::material());

        let output = render_box(&state);

        assert!(output
            .css_variables()
            .contains_key("--rustic_ui_box_padding"));
        assert!(output.inline_style().contains("--rustic_ui_box_padding"));
    }

    #[test]
    fn adapter_props_delegate_to_shared_renderer() {
        let tokens = rustic_ui_headless::r#box::BoxTokens {
            padding: ResponsiveValue::from(String::from("2rem")),
            margin: ResponsiveValue::from(String::from("1rem")),
            background: ResponsiveValue::from(String::from("var(--surface)")),
        };
        let state = BoxState::new(tokens, BreakpointConfig::material());

        let base = render_box(&state);
        let adapter = super::render_box_with_props(BoxAdapterProps::new(&state));

        assert_eq!(base.inline_style(), adapter.inline_style());
    }
}
