[package]
name = "feedback-tooltips"
version = "0.1.0"
edition = "2021"
description = "Multi-framework tooltip blueprints for mui-material."
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
mui-material = { path = "../../crates/mui-material" }
mui-headless = { path = "../../crates/mui-headless" }
mui-styled-engine = { path = "../../crates/mui-styled-engine" }
mui-system = { path = "../../crates/mui-system" }
