[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish = false

[dependencies]
clap = { workspace = true, features = ["derive", "std"] }
anyhow = { workspace = true }
serde_json.workspace = true
toml.workspace = true
rustic-ui-system = { path = "../rustic-ui-system", version = "0.1.0" }
rustic-ui-design-tokens = { path = "../rustic-ui-design-tokens", version = "0.1.0" }
walkdir.workspace = true
serde = { workspace = true }
chrono = { workspace = true }
once_cell = { workspace = true }
regex = "1.10"
pulldown-cmark = { version = "0.9", default-features = false, features = ["simd"] }
swc_common = { version = "14.0.4" }
swc_ecma_ast = { version = "15.0.0", features = ["serde"] }
swc_ecma_parser = { version = "24.0.1", features = ["typescript"] }
headless_chrome = { version = "1.0.18" }
ureq = { version = "2.9", features = ["json"] }
xtask-docs = { path = "../xtask-docs" }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
