[package]
name = "material-parity"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
walkdir = { workspace = true }
heck = { workspace = true }
swc_common = { version = "14.0.4" }
swc_ecma_ast = { version = "15.0.0", features = ["serde"] }
swc_ecma_parser = { version = "24.0.1", features = ["typescript"] }
