[package]
name = "mui-sycamore-example"
version = "0.1.0"
edition = "2021"

[dependencies]
sycamore.workspace = true
rustic-ui-system = { path = "../../crates/rustic-ui-system", features = ["sycamore"] }
tokio = { workspace = true, optional = true }

[features]
default = ["csr"]
csr = []
ssr = ["tokio"]
