[package]
name = "rustic_ui_ssr_accessibility"
version = "0.1.0"
edition = "2021"

[dependencies]
yew.workspace = true
# Tokio runtime enables async server side rendering.
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
rustic-ui-material = { path = "../../crates/rustic-ui-material", features = ["yew"] }
rustic-ui-styled-engine = { path = "../../crates/rustic-ui-styled-engine", features = ["yew"] }
