name: CI

on:
  push:
    branches-ignore:
      # Renovate branches are always Pull Requests.
      # We don't need to run CI twice (push+pull_request)
      - 'renovate/**'
      - 'dependabot/**'
  pull_request:
    paths-ignore:
      # should sync with ci-check.yml as a workaround to bypass github checks
      - 'examples/**'

permissions: {}

jobs:
  continuous-releases:
    name: Continuous releases
    uses: mui/mui-public/.github/workflows/ci-base.yml@master

  # Tests dev-only scripts across all supported dev environments
  test-dev:
    # l10nbot does not affect dev scripts.
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - run: echo "${{ github.actor }}"
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo xtask fmt --check
      - name: Lint with Clippy
        run: cargo xtask clippy
      - name: Run workspace tests
        run: cargo xtask test
      - name: Build Rust-first docs
        run: cargo xtask build-docs
