name: Build canary bundles

on:
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Refresh icon assets
        run: cargo xtask icon-update
      - name: Build canary icon bundles
        run: cargo xtask icons-bundle --compat
      - name: Build canary theme bundles
        run: cargo xtask themes-bundle --compat
      - name: Upload canary bundles
        uses: actions/upload-artifact@v4
        with:
          name: rusticui-canary-bundles
          path: target/artifacts
